With our dependencies added and our basic security config now in place we can go ahead and add our OAuth2 configuration.
In our `application.groovy` go ahead and add the following block.

[source,groovy]
.grails-app/conf/application.groovy
----
include::{sourceDir}/grails-app/conf/application.groovy[indent=0, tag=oauthConfig]
----
<1> Secure the token storage. The secret can be set to any value.
<2> Callback url, after selecting your Facebook user this is where Facebook will attempt to return with your authentication token
<3> Which pac4j client to use; in our case the Facebook client
<4> Your App ID
<5> Your App Secret
<6> Set of Facebook permissions. View Facebook documentation https://developers.facebook.com/docs/facebook-login/permissions[here]
<7> Data fields that are returned to your app from Facebook
<8> Specific roles that Facebook authentication is allowed to access
<9> We are going to authenticate our users only against Google. Thus, we use only the anonymous authentication provider. Read more about https://grails-plugins.github.io/grails-spring-security-core/latest/#authenticationProviders[Authentication Providers] in Spring Security Core Plugin documentation.

Now that we have all our OAuth2 configuration in place lets go ahead and put the rest of our app together.